# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 03:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, verbose_name='标题')),
                ('detail', models.TextField(blank=True, verbose_name='内容')),
                ('postTime', models.DateTimeField(verbose_name='发布时间')),
            ],
        ),
        migrations.CreateModel(
            name='ArticleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeName', models.CharField(max_length=50, verbose_name='类型名称')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='articleType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.ArticleType'),
        ),
    ]
